# Generated by Django 5.2.1 on 2025-06-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contexto', models.CharField(max_length=255)),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.arduino')),
            ],
        ),
    ]
